# Generated by Django 2.0.1 on 2018-01-23 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_eng', models.CharField(max_length=300)),
                ('text_rus', models.CharField(max_length=300)),
                ('text_nor', models.CharField(max_length=300)),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_eng', models.CharField(max_length=300)),
                ('text_rus', models.CharField(max_length=300)),
                ('text_nor', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_eng', models.CharField(max_length=80)),
                ('text_rus', models.CharField(max_length=80)),
                ('text_nor', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_quiz.Section'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_quiz.Question'),
        ),
    ]
