# Generated by Django 2.0.1 on 2018-01-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0003_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='letter',
            field=models.CharField(default='', max_length=1),
        ),
    ]
