# Generated by Django 2.0.1 on 2018-02-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0004_answer_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_number',
            field=models.IntegerField(default=0),
        ),
    ]
