# Generated by Django 2.0.1 on 2018-03-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0008_auto_20180320_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testquestion',
            old_name='number',
            new_name='q_num',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='question',
        ),
        migrations.AddField(
            model_name='testanswer',
            name='q_num',
            field=models.IntegerField(default=0),
        ),
    ]
