# Generated by Django 2.0.1 on 2018-03-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0009_auto_20180321_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='css_class',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_eng',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_nor',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_rus',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_eng',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_nor',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_rus',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='section',
            name='text_eng',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='section',
            name='text_nor',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='section',
            name='text_rus',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='checkbox',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='correct',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='text_eng',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='text_nor',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='text_rus',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='user_answer',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='text_eng',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='text_nor',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='text_rus',
            field=models.CharField(default='', max_length=300),
        ),
    ]
